# Generated by Django 3.2.23 on 2024-01-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zena', '0003_auto_20240114_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='_from',
            new_name='publisher',
        ),
    ]
