# Generated by Django 3.2.23 on 2024-01-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zena', '0004_rename__from_new_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(default='', upload_to='static/'),
        ),
    ]
